apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: upbound
  namespace: upbound-system
spec:
  releaseName: upbound
  chart:
    spec:
      chart: universal-crossplane
      sourceRef:
        kind: HelmRepository
        name: upbound-stable
  interval: 50m
  install:
    remediation:
      retries: 3