apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  releaseName: crossplane
  chart:
    spec:
      chart: crossplane
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    providers:
    - package: xpkg.upbound.io/crossplane-contrib/provider-gcp:v0.22.0